name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]

jobs:
  check-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}.....
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - name: Set up QEMU.....
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx.....
        uses: docker/setup-buildx-action@v1

      - name: Build and push.....
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: thiagosf85/api-node:1.0.0
